//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderDetail
    {
        public int CODID { get; set; }
        public string COID { get; set; }
        public string ProID { get; set; }
        public Nullable<int> CODAmount { get; set; }
        public Nullable<decimal> CODPrice { get; set; }
        public Nullable<int> CODDiscont { get; set; }
        public Nullable<decimal> CODDisPrice { get; set; }
        public Nullable<int> CODSale { get; set; }
        public string CODDesc { get; set; }
    }
}
