//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depots
    {
        public string DepotID { get; set; }
        public string DepotName { get; set; }
        public string DepotMan { get; set; }
        public string DepotTel { get; set; }
        public string DepotAddress { get; set; }
        public string DepotDesc { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> DepotState { get; set; }
    }
}
