//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolveDetail
    {
        public int DevDID { get; set; }
        public string DevID { get; set; }
        public string ProID { get; set; }
        public Nullable<int> DevDAmount { get; set; }
        public string DevDDesc { get; set; }
    }
}
