//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherInDepot
    {
        public string OIDID { get; set; }
        public string DepotID { get; set; }
        public Nullable<System.DateTime> OIDDate { get; set; }
        public Nullable<int> OIDUser { get; set; }
        public Nullable<int> OIDState { get; set; }
        public string OIDDesc { get; set; }
    }
}
