//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotePriceDetail
    {
        public int QPDID { get; set; }
        public string QPID { get; set; }
        public string ProID { get; set; }
        public Nullable<int> QPDAmount { get; set; }
        public Nullable<decimal> QPDPrice { get; set; }
        public Nullable<int> QPDDiscont { get; set; }
        public Nullable<decimal> QPDDisPrice { get; set; }
        public string QPDDesc { get; set; }
    }
}
