//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutDepotDetail
    {
        public int SRDDID { get; set; }
        public int ProID { get; set; }
        public string SRDID { get; set; }
        public int SIDDAmount { get; set; }
        public decimal SIDDPrice { get; set; }
        public string SIDDDesc { get; set; }
    }
}
