//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockReturn()
        {
            this.StockReturnDetail = new HashSet<StockReturnDetail>();
        }
    
        public string SRID { get; set; }
        public string SIDID { get; set; }
        public Nullable<System.DateTime> SRDate { get; set; }
        public Nullable<System.DateTime> SRCreateTime { get; set; }
        public Nullable<int> SRUser { get; set; }
        public Nullable<int> SRState { get; set; }
        public string SRDesc { get; set; }
    
        public virtual StockInDepot StockInDepot { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockReturnDetail> StockReturnDetail { get; set; }
    }
}
