//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInDepot
    {
        public string SIDID { get; set; }
        public string PPID { get; set; }
        public string DepotID { get; set; }
        public string StockID { get; set; }
        public Nullable<System.DateTime> SIDDate { get; set; }
        public string SIDDeliver { get; set; }
        public Nullable<decimal> SIDFreight { get; set; }
        public Nullable<int> SIDUser { get; set; }
        public Nullable<int> SIDData { get; set; }
        public string SIDDesc { get; set; }
    }
}
