//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReturnDetail
    {
        public int SRDID { get; set; }
        public Nullable<int> ProID { get; set; }
        public string SRID { get; set; }
        public Nullable<int> SRDAmount { get; set; }
        public Nullable<decimal> SRDPrice { get; set; }
        public string SRDDesc { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual StockReturn StockReturn { get; set; }
    }
}
